#!/bin/bash
echo "C-Files-------------------------------------------------------------------------" > code.txt
echo "main.c--------------------------------------------------------------------------" >> code.txt
cat ./src/main.c >> code.txt
echo "graphlib.c----------------------------------------------------------------------" >> code.txt
cat ./src/graphlib.c >> code.txt
echo "extralib.c----------------------------------------------------------------------" >> code.txt
cat ./src/extralib.c >> code.txt
echo "cryptolib.c---------------------------------------------------------------------" >> code.txt
cat ./src/cryptolib.c >> code.txt
echo "hashtab.c-----------------------------------------------------------------------" >> code.txt
cat ./src/hashtab.c >> code.txt
echo "Headers-------------------------------------------------------------------------" >> code.txt
echo "main.h--------------------------------------------------------------------------" >> code.txt
cat ./include/main.h >> code.txt
echo "graphlib.h----------------------------------------------------------------------" >> code.txt
cat ./include/graphlib.h >> code.txt
echo "extralib.h----------------------------------------------------------------------" >> code.txt
cat ./include/extralib.h >> code.txt
echo "cryptolib.h---------------------------------------------------------------------" >> code.txt
cat ./include/cryptolib.h >> code.txt
echo "hashtab.h-----------------------------------------------------------------------" >> code.txt
cat ./include/hashtab.h >> code.txt
